export const iconsMenu = {
  save: "💾",
  link: "🔗",
  image: "🖼️",
  post: "📤",
  articles: "📰",
  font: "🎨",
  sections: "▼",
  styles: "🪄",
  menu: "🧰",
  clear: "🌪",
  translate: "🌐",
  english: "🇺🇸",
  spanish: "🇲🇽",
  summary: "📝",
  view: "📄",
  edit: "✏️",
  preview: "🗺️",
};
