import type { Metadata } from "next";
import "./globals.css";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import "sweetalert2/dist/sweetalert2.min.css";
import { Lexend, Inter } from "next/font/google";
import { headers } from "next/headers";

const lexend = Lexend({
  weight: ["400", "700"],
  style: ["normal"],
  subsets: ["latin"],
});

const inter = Inter({
  weight: ["400", "700"],
  style: ["normal"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Your Content Manager Editor",
  description: "Generated by Joel Montes de Oca Lopez",
  generator: "Next.js",
  manifest: "/manifest.json",
  keywords: ["Nextjs", "React", "JavaScript", "pwa", "Typescript"],
  authors: [
    { name: "Joel Montes de Oca Lopez" },
    {
      name: "Joel Montes de Oca Lopez",
      url: "https://joelmontesdeoca.dev",
    },
  ],
  icons: {
    icon: "/favicon.ico",
    apple: "/apple-touch-icon.png",
  },
  other: { "apple-mobile-web-app-title": "Your CMS" },
  robots: {
    index: false,
    follow: false,
  },
};
//
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const nonce = (await headers()).get("x-nonce") || "";

  return (
    <html lang="en" nonce={nonce}>
      <body className={`${lexend.className} ${inter.className}`}>
        {children}
        <SpeedInsights />
        <Analytics />
      </body>
    </html>
  );
}
