import type { Metadata } from "next";
import "./globals.css";
import ReduxProvider from '../services/redux_provider';
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";

export const metadata: Metadata = {
  title: "Your Content Manager Editor",
  description: "Generated by Joel Montes de Oca Lopez",
    generator: "Next.js",
    manifest: "/manifest.json",
    keywords: ["Nextjs", "React", "JavaScript", "pwa", "Typescript"],
    authors: [
      { name: "Joel Montes de Oca Lopez" },
      {
        name: "Joel Montes de Oca Lopez",
        url: "https://joelmontesdeoca.dev",
      },
    ],
    icons: {
      icon: "/favicon.ico",
      apple: "/apple-touch-icon.png"
    },
    other: { "apple-mobile-web-app-title" :  "Your CMS"},
};
//
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
          <ReduxProvider>{children}</ReduxProvider>
          <SpeedInsights />
          <Analytics/>
      </body>
    </html>
  );
}
